### PR TITLE
Update readme with link that will always point to latest phar

### PR DESCRIPTION
**Pull request by erikhansen**
This link format is documented here: https://help.github.com/en/articles/linking-to-releases#linking-to-the-latest-release

### CODE REVIEW

**Comment by peterjaap** [comment]
+:1+ thanks!

**Comment by peterjaap** [comment]
One day too early for Hacktoberfest :sob:  :laughing:

**Comment by erikhansen** [comment]
@peterjaap Haha! Thanks for this great tool! It's far better than the email-only manual anonymization [I have been using](https://gist.github.com/erikhansen/26e59f8c8de749790d146bb48a7d6946#file-sync_prod_to_stage-sh-L87..file-sync_prod_to_stage-sh-L121).

**Comment by peterjaap** [comment]
@erikhansen ha yes that's definitly an improvement. Ps we're building an M2 version of your UntranslatedStrings extension, thanks for that inspriation :)

**Comment by erikhansen** [comment]
@peterjaap I'm sure my former colleague @ericthehacker will be happy to hear that. I'm sure he'd also be happy to link to your M2 extension from the [M1 readme](https://github.com/ericthehacker/magento-untranslatedstrings) once you've released it.

**Comment by peterjaap** [comment]
@erikhansen :+1: 

This might interested you as well bytheway https://github.com/elgentos/masquerade/wiki/How-to-run-Masquerade-nightly-with-Gitlab-CI-CD

**Pull request closed without merging**
