### PR TITLE
Fixes #48: Added config for sales_order_payment table

### LINKED ISSUE #48: Masquerade (out of the box) doesn't anonymise Paypal payment detail
I wasn't sure whether this is in scope or not as I'm sure most merchants run third-party payment methods. However, considering that Paypal is shipped with Magento, I probably would have expected this to happen.

### PR DESCRIPTION
**Pull request by erfanimani**

### CODE REVIEW

**Comment by peterjaap** [comment]
@erfanimani doesn't using an empty value throw an error? Shouldn't it be `{}`?

**Comment by erfanimani** [comment]
Actually, an empty value works too. Only if the row doesn't exist, it
throws the error.

I also tried it with {}, and I couldn't get it working. It seemed to me
that the fixed formatter only works with an empty value.

(If I specified the value as {}, or anything else for that matter, it just
set it to empty.)

**Comment by peterjaap** [comment]
Thanks! 

I created a new issue for the fixed formatter https://github.com/elgentos/masquerade/issues/67

**Comment by peterjaap** [comment]
https://github.com/elgentos/masquerade/releases/tag/0.2.5

**Pull request merged**
