### PR TITLE
Remove table alias

### LINKED ISSUE #70: delete: true gives errors
@johnorourke I just ran into this;

```
PHP Notice:  Undefined index: columns in phar:///usr/bin/masquerade/src/Elgentos/Masquerade/DataProcessor/DefaultDataProcessorFactory.php on line 27
PHP Warning:  Invalid argument supplied for foreach() in phar:///usr/bin/masquerade/src/Elgentos/Masquerade/DataProcessor/DefaultDataProcessorFactory.php on line 27
PHP Notice:  Array to string conversion in phar:///usr/bin/masquerade/src/Elgentos/Masquerade/Console/SymfonyOutput.php on line 92
Deleting records from Array table
In Connection.php line 669:
                                                                               
  SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error i  
  n your SQL syntax; check the manual that corresponds to your MySQL server v  
  ersion for the right syntax to use near 'as `main`' at line 1 (SQL: delete   
  from `swissup_checkoutfields_values` as `main`)                              
                                                                               
In PDOConnection.php line 72:
                                                                               
  SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error i  
  n your SQL syntax; check the manual that corresponds to your MySQL server v  
  ersion for the right syntax to use near 'as `main`' at line 1                
                                                                               
In PDOConnection.php line 67:
                                                                               
  SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error i  
  n your SQL syntax; check the manual that corresponds to your MySQL server v  
  ersion for the right syntax to use near 'as `main`' at line 1    
```

This is the yaml file I'm using; https://github.com/elgentos/masquerade/wiki/Swissup-YAML-file

Any idea?

### PR DESCRIPTION
**Pull request by Tjitse-E**
Fixes #70 - the alias breaks the delete option.

I did a test without the table alias and It didn't break anything. I also searched the source code for the alias and I couldn't find anything.

### CODE REVIEW

**Comment by peterjaap** [comment]
@IvanChepurnyi why was this alias introduced in the first place?

**Comment by IvanChepurnyi** [comment]
@peterjaap It should not be removed as a table alias is required for EAV table joins.

**Comment by IvanChepurnyi** [comment]
Created @Tjitse-E @peterjaap created Pull Request to fix the issue by preserving prefix for select queries.

**Comment by Tjitse-E** [comment]
Great!

**Pull request closed without merging**
