### PR TITLE
Redesign of database components to process anonymization extremely fast

### PR DESCRIPTION
**Pull request by IvanChepurnyi**
Key features of the current redesign:

- Significant improvement in the performance of anonymization
- More feedback during process execution
- Removed inheritance as an extension mechanism

Prior to these changes, a database with 2 million quotes, 300k customers, and tons of orders was taking around 2 days to complete, after this PR it takes only 17 minutes total.

### CODE REVIEW

**Comment by peterjaap** [comment]
@IvanChepurnyi awesome! 

I just tried building the phar file, but it gives me this error (the current HEAD does build);

```
 ~/development/workspace/elgentos/ecomdev-masquerade   refactor-into-superfast-tool  php -d phar.readonly=off ./box.phar compile -vvv
                                                     
Box Requirements Checker
========================
                                                     
> Using PHP 7.4.16  
> PHP is using the following php.ini file:
  /usr/local/etc/php/php.ini
                                                     
> Checking Box requirements:
  ✔ The application requires the version "^7.3" or greater.                                                                                                                                                          
  ✔ The application requires the extension "zlib".
  ✔ The application requires the extension "phar".                                                                                                                                                                   
  ✔ The package "beberlei/assert" requires the extension "json".                                                                                                                                                     
  ✔ The package "beberlei/assert" requires the extension "simplexml".                                                                                                                                                
  ✔ The package "nikic/php-parser" requires the extension "tokenizer".
   
                                                                                                                                                                                                                     
 [OK] Your system is ready to run the application.                              
                                                                                                                                                                                                                                                                                                                                                                                                                                          
[debug] Current memory limit: "512MB"                                                                                                                                                                                [debug] Checking BOX_ALLOW_XDEBUG                                                                                                                                                                                    
[debug] phar.readonly is disabled                                                                                                                                                                                    [debug] The Xdebug extension is loaded (3.0.3)                                                            
[debug] Async signals enabled (SIGINT = SIG_IGN)
[debug] Process restarting (BOX_ALLOW_XDEBUG=internal|3.0.3|1|*|*)                                                                                                                                                   
[debug] Running '/usr/local/bin/php' './box.phar' 'compile' '-vvv' '--ansi'
                                                                                                                                                                                                                     Box Requirements Checker                                                                                                                                                                                             
========================                                                                                                                                                                                                                                                                                                                                                                                                                  
> Using PHP 7.4.16                                                                                                                                                                                                   > PHP is using the following php.ini file:                                                                
  /tmp/zVvqd1                       

                                                                                
 [OK] Your system is ready to run the application.                              
                                                                                

[debug] Current memory limit: "512MB"
[debug] Checking BOX_ALLOW_XDEBUG
[debug] Restarted (57 ms). The Xdebug extension is not loaded
[debug] Async signals enabled (SIGINT = SIG_DFL)

    ____            
   / __ )____  _  __
  / __  / __ \| |/_/
 / /_/ / /_/ />  <  
/_____/\____/_/|_|  
                    

Box version 3.10.0@458a695 2020-11-30 13:20:30 UTC

 // Loading the configuration file "/data/elgentos/ecomdev-masquerade/box.json".                                        

                                                                                                                        
 [ERROR] The configuration file is invalid.                                                                             
                                                                                                                        


PHP Fatal error:  Uncaught Error: Call to undefined function get_debug_type() in phar:///data/elgentos/ecomdev-masquerade/box.phar/vendor/symfony/console/Application.php:528
Stack trace:
#0 phar:///data/elgentos/ecomdev-masquerade/box.phar/vendor/symfony/console/Application.php(521): _HumbugBox64b6b26b2285\Symfony\Component\Console\Application->doActuallyRenderThrowable(Object(_HumbugBox64b6b26b2285\Assert\InvalidArgumentException), Object(_HumbugBox64b6b26b2285\Symfony\Component\Console\Output\StreamOutput))
#1 phar:///data/elgentos/ecomdev-masquerade/box.phar/vendor/symfony/console/Application.php(496): _HumbugBox64b6b26b2285\Symfony\Component\Console\Application->doRenderThrowable(Object(_HumbugBox64b6b26b2285\Assert\InvalidArgumentException), Object(_HumbugBox64b6b26b2285\Symfony\Component\Console\Output\StreamOutput))
#2 phar:///data/elgentos/ecomdev-masquerade/box.phar/vendor/symfony/console/Application.php(86): _HumbugBox64b6b26b2285\Symfony\Component\Console\Application->renderThrowable(Object(_HumbugBox64b6b26b2285\As in phar:///data/elgentos/ecomdev-masquerade/box.phar/vendor/symfony/console/Application.php on line 528

Fatal error: Uncaught Error: Call to undefined function get_debug_type() in phar:///data/elgentos/ecomdev-masquerade/box.phar/vendor/symfony/console/Application.php:528
Stack trace:
#0 phar:///data/elgentos/ecomdev-masquerade/box.phar/vendor/symfony/console/Application.php(521): _HumbugBox64b6b26b2285\Symfony\Component\Console\Application->doActuallyRenderThrowable(Object(_HumbugBox64b6b26b2285\Assert\InvalidArgumentException), Object(_HumbugBox64b6b26b2285\Symfony\Component\Console\Output\StreamOutput))
#1 phar:///data/elgentos/ecomdev-masquerade/box.phar/vendor/symfony/console/Application.php(496): _HumbugBox64b6b26b2285\Symfony\Component\Console\Application->doRenderThrowable(Object(_HumbugBox64b6b26b2285\Assert\InvalidArgumentException), Object(_HumbugBox64b6b26b2285\Symfony\Component\Console\Output\StreamOutput))
#2 phar:///data/elgentos/ecomdev-masquerade/box.phar/vendor/symfony/console/Application.php(86): _HumbugBox64b6b26b2285\Symfony\Component\Console\Application->renderThrowable(Object(_HumbugBox64b6b26b2285\As in phar:///data/elgentos/ecomdev-masquerade/box.phar/vendor/symfony/console/Application.php on line 528
[debug] Restarted process exited 255
```

**Comment by IvanChepurnyi** [comment]
@peterjaap Any news on merge ETA?

**Comment by peterjaap** [comment]
@peterjaap I'm on vacation this week, I'll check my pipelines next week to see if they ran into issues

**Comment by peterjaap** [comment]
Haven't had any issues! Tagging 0.3.0 now.

**Pull request merged**
