### PR TITLE
Allow EAV and other extended table types

### PR DESCRIPTION
**Pull request by johnorourke**
Working with Magento2 EAV.

This adds 'table providers' - so new types of complex table can be added either by the end user or within the package.

See `src/config/sample/magento_eav.yaml` for example config.

It also adds new 'where' and 'delete' options at table level, so you can truncate tables you don't need or only affect certain data - for example, to leave data alone which is used by unit tests.

This opens the door for adding table types for Wordpress and Drupal, which have their own linked-table systems - eg. in a Wordpress table provider, we'd be able to specify 'postmeta' fields to be anonymised, simply by adding a new class.

See the updates in README.md for more info and see examples in `src/config/sample`.

### CODE REVIEW

**Comment by johnorourke** [comment]
(hang fire on this - just ironing out a couple of issues found when moving into prod)

**Comment by peterjaap** [comment]
@johnorourke thanks for working on this! I'll wait with testing until you give me the green light :)

**Comment by johnorourke** [comment]
OK @peterjaap it's working for me nicely now, including accurate row counts and EAV attributes with per-store values.

There's an issue with Illuminate where `->count()` doesn't behave as expected when using groupBy or having - fixed in 7.x but I've put a workaround in so that we don't need to upgrade it, meaning this will still work with php 7.1.  See https://github.com/laravel/framework/pull/32624

**Comment by johnorourke** [comment]
@peterjaap In production we discovered one more issue - the 'delete' option does not enforce integrity, so any foreign keys with 'on delete cascade' triggers are not deleted, leaving invalid data. I'll add a fix.

**Comment by johnorourke** [comment]
@peterjaap still not getting 'on delete cascade' enforced, so don't test/merge this yet!

**Comment by johnorourke** [comment]
@peterjaap I'm happy with this now - I updated the README with much more detail about how to use EAV, 'delete' and 'where' options, and added a new 'platform' setting of 'magento2-without-orders' to give a better example of removing data.

**Pull request merged**
